---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
  name: {{ include "kubensync-operator.fullname" . }}-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubensync-operator.fullname" . }}-kubensync-namespace-reader
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubensync-operator.fullname" . }}-manager-role
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - automation.kubensync.com
  resources:
  - managedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.kubensync.com
  resources:
  - managedresources/finalizers
  verbs:
  - update
- apiGroups:
  - automation.kubensync.com
  resources:
  - managedresources/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
  name: {{ include "kubensync-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
  name: {{ include "kubensync-operator.fullname" . }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
  name: {{ include "kubensync-operator.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubensync-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubensync-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubensync-operator.fullname" . }}-kubensync-namespace-reader-binding
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubensync-operator.fullname" . }}-kubensync-namespace-reader
subjects:
- kind: ServiceAccount
  name: {{ include "kubensync-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubensync-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubensync-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
  name: {{ include "kubensync-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubensync-operator.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubensync-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}