apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubensync-operator.fullname" . }}-metrics-service
  labels:
    {{- include "kubensync-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "kubensync-operator.selectorLabels" . | nindent 4 }}
