apiVersion: v1
entries:
  kubensync-operator:
  - apiVersion: v2
    appVersion: v0.4.0
    created: "2024-11-30T01:15:37.492817266+01:00"
    description: A Helm chart for installing the kubensync-operator.
    digest: 895c1ad9c5f61b7bdc74a20e57b2291b61cc6a307327c04e700145b16b69da2b
    maintainers:
    - email: eryalito@gmail.com
      name: eryalito
      url: https://eryalito.dev
    name: kubensync-operator
    type: application
    urls:
    - kubensync-operator-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-30T01:15:37.491833447+01:00"
