apiVersion: automation.kubensync.com/v1alpha1
kind: ManagedResource
metadata:
  labels:
    app.kubernetes.io/name: kubensync
    app.kubernetes.io/managed-by: kustomize
  name: managedresource-sample
spec:
  # TODO(user): Add fields here
