name: Automerge release PRs

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      pr_number:
        required: true
        type: string
    secrets:
      repo_creds:
        required: true
      pat_creds:
        required: true

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Automerge PR
        run: |
          echo ${{ secrets.pat_creds }} | gh auth login --with-token
          gh pr review ${{ inputs.pr_number }} --approve
          gh pr merge ${{ inputs.pr_number }} --auto --squash
