name: Build and Publish Operator

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      repo_creds:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: v${{ inputs.version }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install Operator SDK
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.28.0/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64
          sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

      - name: Update version & variables
        run: |
          sed -i "s|CHANGE_ME_VERSION|${{ inputs.version }}|" config/manager/kustomization.yaml
          sed -i "s|CHANGE_ME_VERSION|${{ inputs.version }}|" Makefile
          sed -i "s|CHANGE_ME_IMAGE|ghcr.io/${{ github.repository }}|" config/manager/kustomization.yaml
          sed -i "s|CHANGE_ME_IMAGE|ghcr.io/${{ github.repository }}|" Makefile

      - name: Generate manifests
        run: make bundle

      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.repo_creds }}

      - name: Build bundle
        run: |
          make bundle-build bundle-push

      - name: Test bundle
        run: |
          operator-sdk bundle validate ghcr.io/${{ github.repository }}-bundle:v${{ inputs.version }}

      - name: Build operator
        run: |
          make docker-build docker-push
