name: Tests e2e

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:

jobs:
  test:
    name: Run on Ubuntu with k8s v${{ matrix.k8s_version }}
    runs-on: ubuntu-latest
    if: '!contains(github.event.pull_request.labels.*.name, ''skip-ci'')'
    strategy:
      matrix:
        k8s_version:
          - "1.28"
          - "1.29"
          - "1.30"
          - "1.31"
          - "1.32"
          - "1.33"
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Build operator
        run: |
          IMG=ghcr.io/${{ github.repository }}:v0.0.0-e2e-test make docker-build
          IMG=ghcr.io/${{ github.repository }}:v0.0.0-e2e-test make build-installer

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: e2e-test
          node_image: kindest/node:v${{ matrix.k8s_version }}.0

      - name: Load operator image into Kind Cluster
        run: |
          kind load docker-image --name e2e-test ghcr.io/${{ github.repository }}:v0.0.0-e2e-test

      - name: Run e2e tests
        run: |
          /bin/bash e2e/pre.sh && /bin/bash e2e/test.sh && /bin/bash e2e/post.sh
